### ISSUE TITLE
Failed to install on Debian 9 server - serialport module issue

### ISSUE THREAD

**Issue by hetlelid** [monteslu/pagenodes#103]
Was not able to install by `npm install`, see below.

I can see the serialport module is an old revision. What is the options? I would like to create a PWA enabled NodeRed like dashboard.

/var/www/html/pagenodesgit/pagenodes/node_modules/.bin/touch: 1: /var/www/html/pagenodesgit/pagenodes/node_modules/.bin/touch: Syntax error: "(" unexp
ected
serialport.target.mk:103: recipe for target 'Release/obj.target/serialport/src/serialport.o' failed
make: *** [Release/obj.target/serialport/src/serialport.o] Error 2
make: Leaving directory '/var/www/html/pagenodesgit/pagenodes/node_modules/serialport/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.9.0-6-amd64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/var/www/ht
ml/pagenodesgit/pagenodes/node_modules/serialport/build/Release/serialport.node" "--module_name=serialport" "--module_path=/var/www/html/pagenodesgit/
pagenodes/node_modules/serialport/build/Release"
gyp ERR! cwd /var/www/html/pagenodesgit/pagenodes/node_modules/serialport
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-bu
ild --module=/var/www/html/pagenodesgit/pagenodes/node_modules/serialport/build/Release/serialport.node --module_name=serialport --module_path=/var/ww
w/html/pagenodesgit/pagenodes/node_modules/serialport/build/Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/var/www/html/pagenodesgit/pagenodes/node_modules/serialport/node_modules/node-pre-gyp/lib/ut
il/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.9.0-6-amd64
node-pre-gyp ERR! command "/usr/bin/node" "/var/www/html/pagenodesgit/pagenodes/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--f
allback-to-build"
node-pre-gyp ERR! cwd /var/www/html/pagenodesgit/pagenodes/node_modules/serialport
node-pre-gyp ERR! node -v v8.12.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/var/www/html/page
nodesgit/pagenodes/node_modules/serialport/build/Release/serialport.node --module_name=serialport --module_path=/var/www/html/pagenodesgit/pagenodes/n
ode_modules/serialport/build/Release' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","ar
ch":"x64"})
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serialport@4.0.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1

**Comment by monteslu** [comment]
fixed in #109
